providers = ['node']
buildImage = 'ghcr.io/railwayapp/nixpacks:ubuntu-1731369831'

[variables]
CI = 'true'
NIXPACKS_METADATA = 'node'
NODE_ENV = 'production'
NPM_CONFIG_PRODUCTION = 'false'


[phases.setup]
nixPkgs = ['nodejs_22', 'pnpm-9_x', 'openssl']
nixLibs = ['gcc-unwrapped']
nixOverlays = [
  'https://github.com/railwayapp/nix-npm-overlay/archive/main.tar.gz',
]
nixpkgsArchive = 'e05605ec414618eab4a7a6aea8b38f6fbbcc8f08'


[phases.install]
dependsOn = ['setup']
cmds = ['NODE_OPTIONS=--no-deprecation pnpm i --frozen-lockfile']
cacheDirectories = ['/root/.local/share/pnpm/store/v3']
paths = ['/app/node_modules/.bin']


[phases.build]
dependsOn = ['install']
cmd = 'cross-env NODE_OPTIONS=--no-deprecation next build'
cacheDirectories = ['.next/cache', 'node_modules/.cache']


[start]
cmd = 'cross-env NODE_OPTIONS=--no-deprecation next start -p 8080'
